### ISSUE TITLE
Doesn't work with <a name="named-anchor">

### ISSUE THREAD

**Issue by henrahmagix** [jonaskuske/smoothscroll-anchor-polyfill#33]
Instead of using `id`s, I'm using anchors with `name` attribute, e.g.
```html
<nav>
	<a href="#heading">Heading</a>
	<a href="#footer">Footer</a>
</nav>

<a name="heading"></a>
<h2>Heading</h2>

<a name="footer"></a>
<footer>Page footer</footer>
```

This polyfill won't look for `a[name="heading"]` when clicking the related nav link, so smooth scrolling doesn't happen, where it does if I change `name="heading"` to `id="heading"`.

Love this otherwise =)

**Comment by jonaskuske** [comment]
Hey!

This was by design, as the name attribute on anchors is obsolete in HTML5 (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#name), so I decided not to implement it.  
Any reason you can't use `id` to target elements? Might be willing to reconsider if there are still reasons that make `name` necessary :)

**Comment by henrahmagix** [comment]
I ended up switching to `id`s because Safari wasn't focusing the anchor with just `name` =) soooo...

> This was by design, as the name attribute on anchors is obsolete in HTML5

Makes total sense, and explains the odd results I got from using `name`!

Thanks for responding so clearly and kindly =)
