### ISSUE TITLE
  window.scrollTo with behavior: 'smooth' doesn't scroll to the top of the page with safari

### ISSUE THREAD

**Issue by ieozt38** [jonaskuske/smoothscroll-anchor-polyfill#38]
On Safari code below doesn't scroll to the top of the page however on other browsers it does. When I delete smooth-scrolling, it scrolls back to the top.  (Angular 10) script added in index.html.

```
       window.scrollTo({
          behavior: 'smooth',
          top: 0,
          left: 0,
        }); 
```

**Comment by jonaskuske** [comment]
Couldn't reproduce this - might be caused by some CSS that makes `<body>` scrollable instead of `<html>`?

Anyway, you'll need to file your issue over at [iamdustan/smoothscroll](https://github.com/iamdustan/smoothscroll), this library here is just concerned with calling the scroll APIs in the right moments (clicks on anchors, forwards/backwards nav...), not with the scroll implementation itself. :)
