### ISSUE TITLE
I can't get it to work in a React NextJS project

### ISSUE THREAD

**Issue by oahmaro** [jonaskuske/smoothscroll-anchor-polyfill#47]
I followed every step in you documentation, and i just can't get it to work on a NextJS application

**Comment by jonaskuske** [comment]
Can you show me a reproduction? I'm afraid this isn't enough information to help.

**Comment by jonaskuske** [comment]
This happens because Next calls `event.preventDefault()` on any link click and handles both the navigation [and the scroll internally](https://github.com/vercel/next.js/blob/84720697e4f00bd77689153f7cf39421be9b1d25/packages/next/shared/lib/router/router.ts#L1650-L1671), so `smoothscroll-anchor-polyfill` can't intercept.

You can try the [`scroll-behavior-polyfill`](https://www.npmjs.com/package/scroll-behavior-polyfill) package, it should work even with 3rd-party code that intercepts and calls `.preventDefault()` like Next.js does. (but has some other trade-offs)
